### ISSUE TITLE
Low training speed

### ISSUE THREAD

**Issue by KangchengLiu** [Gaozhongpai/PaiConvPointSeg#1]
The training speed is very low compared to the original Randla-Net due to large CPU consumption. I wonder what's wrong with it, thanks.

**Comment by Gaozhongpai** [comment]
> The training speed is very low compared to the original Randla-Net due to large CPU consumption. I wonder what's wrong with it, thanks.

The framework was borrowed from Randla-Net. We only replaced the convolutional operation. We use one convolutional operation in a residual block while RandLA-Net uses two. The training speed is faster for us. 

You can replace the residual block to https://github.com/Gaozhongpai/PaiConvPointSeg/blob/a18e42da08dc50e94cd68e7ff351d7db03881e74/PAIConv.py#L382 

which is the original RandLA-Net operation and compare the speed.

**Comment by KangchengLiu** [comment]
But the training speed is indeed slow with your current implementation with 2080TI GPU and tensorflow-gpu-2.0. It took approximately 5s to finish a batch with large CPU utilization. I wonder what's wrong with it, thanks.
